### ISSUE TITLE
Impossible install requirements

### ISSUE THREAD

**Issue by shadow-light** [brechtm/rinoh-typeface-dejavuserif#1]
Hi, just reporting an issue I'm getting in a build.

It appears this project requires `rinohtype>=0.4.3` but at the time of comment this is greater than any version that's been published. Highest version is 0.4.2 at time of writing.

https://pypi.org/project/rinohtype/#history

**Comment by shadow-light** [comment]
I can see a version was yanked. Looks like buildout doesn't detect this yet and installs anyway.

**Comment by brechtm** [comment]
Sorry about that. I released rinoh-typeface-dejavuserif 0.1.2 to fix a warning output by the upcoming rinohtype 0.4.3. However, I when I realized that it would break older rinohtype versions I yanked the release. I'm planning on releasing 0.1.3 that should work for both 0.4.3 and older versions.

Please file a bug report with buildout to handle yanked releases though.

**Comment by brechtm** [comment]
I just released v0.1.3 that should be compatible with rinohtype 0.4.2 and the upcoming release.
